# Projeto 02 - Satisfação do cliente com a experiência de compra online

- Pedro Domitti de Carvalho RA: 21005320
- Vinicus Augusto Papa Batista RA: 21004792
- Igor Roelli Silva RA: 21003696

In [108]:
import pandas as pd
import statsmodels.api as sm

## Pré-processamento dos dados

In [109]:
df = pd.read_excel('../data/online-shopping.xlsx')

df.head()

,ID,Start time,Completion time,Email,Name,Last modified time,Com que frequência você faz compras online?,Qual é a sua faixa etária?,Gênero,Qual é seu nível de satisfação com a interface do usuário de sites/aplicativos de compras online?,Quão satisfeito você está com a variedade de produtos disponíveis online?,"Numa escala de 1 a 5, quão satisfeito você está com os preços dos produtos online?",Com que frequência você encontra problemas técnicos ao fazer compras online?,Qual plataforma de compras online você prefere?,Qual é a probabilidade de você recomendar compras online a um amigo ou colega?,"Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,...","Em média, quanto você gasta em compras online?"
0,1,2024-05-10 09:17:28,2024-05-10 09:18:26,anonymous,NaN,NaN,1 vez por mês,18-24 anos,Masculino,5,5,5,Raramente,Amazon,5,Conveniência;Avaliações;Desconto/Promoções;Preço;,300
1,2,2024-05-10 09:17:02,2024-05-10 09:18:38,anonymous,NaN,NaN,1 vez a cada 2 à 6 meses,18-24 anos,Masculino,4,5,4,Raramente,Mercado livre,5,Preço;,100
2,3,2024-05-10 09:18:27,2024-05-10 09:19:39,anonymous,NaN,NaN,1 vez por mês,18-24 anos,Masculino,5,5,5,Às vezes,kabum,5,Preço;,200
3,4,2024-05-10 09:18:25,2024-05-10 09:19:51,anonymous,NaN,NaN,1 vez por mês,18-24 anos,Masculino,4,4,4,Raramente,Amazon,5,Conveniência;Preço;Avaliações;Desconto/Promoções;,200
4,7,2024-05-10 09:19:29,2024-05-10 09:21:14,anonymous,NaN,NaN,1 vez a cada 6 à 12 meses,18-24 anos,Masculino,3,4,3,Raramente,Amazon,4,Preço;Avaliações;Reputação da Marca;,200

In [110]:
# Drop colunas desnecessárias
df = df.drop(columns=['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time'])

# Drop valores nulos
df = df.dropna()

# Transformar os nomes das plataformas para minúsculo e tirar espaços extras
df.iloc[:, 7] = df.iloc[:, 7].str.lower()
df.iloc[:, 7] = df.iloc[:, 7].str.strip()

df.head()

,Com que frequência você faz compras online?,Qual é a sua faixa etária?,Gênero,Qual é seu nível de satisfação com a interface do usuário de sites/aplicativos de compras online?,Quão satisfeito você está com a variedade de produtos disponíveis online?,"Numa escala de 1 a 5, quão satisfeito você está com os preços dos produtos online?",Com que frequência você encontra problemas técnicos ao fazer compras online?,Qual plataforma de compras online você prefere?,Qual é a probabilidade de você recomendar compras online a um amigo ou colega?,"Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,...","Em média, quanto você gasta em compras online?"
0,1 vez por mês,18-24 anos,Masculino,5,5,5,Raramente,amazon,5,Conveniência;Avaliações;Desconto/Promoções;Preço;,300
1,1 vez a cada 2 à 6 meses,18-24 anos,Masculino,4,5,4,Raramente,mercado livre,5,Preço;,100
2,1 vez por mês,18-24 anos,Masculino,5,5,5,Às vezes,kabum,5,Preço;,200
3,1 vez por mês,18-24 anos,Masculino,4,4,4,Raramente,amazon,5,Conveniência;Preço;Avaliações;Desconto/Promoções;,200
4,1 vez a cada 6 à 12 meses,18-24 anos,Masculino,3,4,3,Raramente,amazon,4,Preço;Avaliações;Reputação da Marca;,200

In [111]:
# Modelo de Regressão Linear

# Variável dependente
X = df.iloc[:, 0:-1]

# Transformar variáveis categóricas em variáveis dummy
X = pd.get_dummies(X, drop_first=True)

X = X.astype(int)

# Variável independente
y = df['Em média, quanto você gasta em compras online?']

# Modelo de Regressão Linear
model = sm.OLS(y, sm.add_constant(X)).fit()

# Resultados
model.summary(title='Regressão Linear')

<class 'statsmodels.iolib.summary.Summary'>
"""
                                             Regressão Linear
==========================================================================================================
Dep. Variable:     Em média, quanto você gasta em compras online?   R-squared:                       1.000
Model:                                                        OLS   Adj. R-squared:                  1.000
Method:                                             Least Squares   F-statistic:                 2.052e+28
Date:                                            Fri, 07 Jun 2024   Prob (F-statistic):           5.49e-71
Time:                                                    14:55:05   Log-Likelihood:                 1086.7
No. Observations:                                              40   AIC:                            -2103.
Df Residuals:                                                   5   BIC:                            -2044.
Df Model:                                                      34
Covariance Type:                                        nonrobust
==========================================================================================================================================================================================================================================================================================================================================================================
                                                                                                                                                                                                                                                                                                             coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                                                                                                                                                                                                                     44.1254   1.03e-12   4.29e+13      0.000      44.125      44.125
Qual é seu nível de satisfação com a interface do usuário de sites/aplicativos de compras online?                                                                                                                                                                                                        -29.6540   4.91e-13  -6.04e+13      0.000     -29.654     -29.654
Quão satisfeito você está com a variedade de produtos disponíveis online?                                                                                                                                                                                                                                 10.1633   3.97e-13   2.56e+13      0.000      10.163      10.163
Numa escala de 1 a 5, quão satisfeito você está com os preços dos produtos online?                                                                                                                                                                                                                         4.0084   3.86e-13   1.04e+13      0.000       4.008       4.008
Qual é a probabilidade de você recomendar compras online a um amigo ou colega?                                                                                                                                                                                                                           105.4706   6.56e-13   1.61e+14      0.000     105.471     105.471
Com que frequência você faz compras online?_1 vez a cada 6 à 12 meses                                                                                                                                                                                                                                   -206.7877   8.69e-13  -2.38e+14      0.000    -206.788    -206.788
Com que frequência você faz compras online?_1 vez por mês                                                                                                                                                                                                                                               -147.3896   8.98e-13  -1.64e+14      0.000    -147.390    -147.390
Com que frequência você faz compras online?_1 vez por semana                                                                                                                                                                                                                                            -127.6126      1e-12  -1.27e+14      0.000    -127.613    -127.613
Com que frequência você faz compras online?_Mais de uma vez por semana                                                                                                                                                                                                                                    39.5651   7.34e-13   5.39e+13      0.000      39.565      39.565
Qual é a sua faixa etária?_25-34 anos                                                                                                                                                                                                                                                                    -61.2807   5.64e-13  -1.09e+14      0.000     -61.281     -61.281
Qual é a sua faixa etária?_35-44 anos                                                                                                                                                                                                                                                                     74.0798   5.94e-13   1.25e+14      0.000      74.080      74.080
Qual é a sua faixa etária?_45-60 anos                                                                                                                                                                                                                                                                     18.8914   7.56e-13    2.5e+13      0.000      18.891      18.891
Qual é a sua faixa etária?_Mais de 60 anos                                                                                                                                                                                                                                                               602.9807   1.71e-12   3.53e+14      0.000     602.981     602.981
Qual é a sua faixa etária?_Menos de 18 anos                                                                                                                                                                                                                                                             -432.7532   1.33e-12  -3.25e+14      0.000    -432.753    -432.753
Gênero _Masculino                                                                                                                                                                                                                                                                                       -103.6315   6.77e-13  -1.53e+14      0.000    -103.631    -103.631
Com que frequência você encontra problemas técnicos ao fazer compras online?_Raramente                                                                                                                                                                                                                    22.4566   5.76e-13    3.9e+13      0.000      22.457      22.457
Com que frequência você encontra problemas técnicos ao fazer compras online?_Às vezes                                                                                                                                                                                                                    -58.2302   6.79e-13  -8.57e+13      0.000     -58.230     -58.230
Qual plataforma de compras online você prefere? _aliexpress                                                                                                                                                                                                                                              -38.4992    7.7e-13     -5e+13      0.000     -38.499     -38.499
Qual plataforma de compras online você prefere? _amazon                                                                                                                                                                                                                                                  -37.3900   4.29e-13  -8.71e+13      0.000     -37.390     -37.390
Qual plataforma de compras online você prefere? _ifood                                                                                                                                                                                                                                                  -206.2528   1.22e-12  -1.69e+14      0.000    -206.253    -206.253
Qual plataforma de compras online você prefere? _kabum                                                                                                                                                                                                                                                   105.0570   7.79e-13   1.35e+14      0.000     105.057     105.057
Qual plataforma de compras online você prefere? _magalu                                                                                                                                                                                                                                                  -23.7188    7.4e-13  -3.21e+13      0.000     -23.719     -23.719
Qual plataforma de compras online você prefere? _mercado livre                                                                                                                                                                                                                                          -248.6649   9.86e-13  -2.52e+14      0.000    -248.665    -248.665
Qual plataforma de compras online você prefere? _netshoes                                                                                                                                                                                                                                                336.7891   1.35e-12   2.49e+14      0.000     336.789     336.789
Qual plataforma de compras online você prefere? _nike                                                                                                                                                                                                                                                    154.7474   8.56e-13   1.81e+14      0.000     154.747     154.747
Qual plataforma de compras online você prefere? _pichau                                                                                                                                                                                                                                                  112.5790   6.27e-13    1.8e+14      0.000     112.579     112.579
Qual plataforma de compras online você prefere? _shein                                                                                                                                                                                                                                                   138.3321   4.41e-13   3.14e+14      0.000     138.332     138.332
Qual plataforma de compras online você prefere? _shopee                                                                                                                                                                                                                                                  -92.7644   9.99e-13  -9.29e+13      0.000     -92.764     -92.764
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Conveniência;Avaliações;Desconto/Promoções;Preço;                                                 71.8872   1.17e-12   6.12e+13      0.000      71.887      71.887
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Conveniência;Preço;Avaliações;Desconto/Promoções;                                                -43.5951   9.01e-13  -4.84e+13      0.000     -43.595     -43.595
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Conveniência;Preço;Desconto/Promoções;                                                           -76.7031   1.07e-12  -7.15e+13      0.000     -76.703     -76.703
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Conveniência;Preço;Desconto/Promoções;Avaliações;                                                -20.8346   1.09e-12   -1.9e+13      0.000     -20.835     -20.835
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Conveniência;Preço;Desconto/Promoções;Avaliações;Reputação da Marca;                            -296.2339   9.85e-13  -3.01e+14      0.000    -296.234    -296.234
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Conveniência;Preço;Seleção de Produtos;Avaliações;Reputação da Marca;                            367.6856   1.51e-12   2.43e+14      0.000     367.686     367.686
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Desconto/Promoções;Reputação da Marca;Avaliações;Preço;                                          335.2937   1.17e-12   2.87e+14      0.000     335.294     335.294
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;                                                                                           -89.8731   7.97e-13  -1.13e+14      0.000     -89.873     -89.873
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Avaliações;                                                                               -156.0890    1.3e-12   -1.2e+14      0.000    -156.089    -156.089
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Avaliações;Desconto/Promoções;                                                             215.5975   8.84e-13   2.44e+14      0.000     215.598     215.598
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Avaliações;Reputação da Marca;                                                              95.6281   9.48e-13   1.01e+14      0.000      95.628      95.628
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Conveniência;Avaliações;                                                                   118.3982    7.7e-13   1.54e+14      0.000     118.398     118.398
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Conveniência;Avaliações;Desconto/Promoções;                                                210.1269   1.59e-12   1.32e+14      0.000     210.127     210.127
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Desconto/Promoções;                                                                        138.3321   4.41e-13   3.14e+14      0.000     138.332     138.332
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Desconto/Promoções;Avaliações;                                                             192.1303   1.12e-12   1.71e+14      0.000     192.130     192.130
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Reputação da Marca;                                                                        -36.2286   8.44e-13  -4.29e+13      0.000     -36.229     -36.229
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Reputação da Marca;Desconto/Promoções;                                                    -210.8364   1.19e-12  -1.77e+14      0.000    -210.836    -210.836
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Seleção de Produtos;                                                                      -163.0688   1.28e-12  -1.27e+14      0.000    -163.069    -163.069
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Seleção de Produtos;Avaliações;                                                            184.2562    1.6e-12   1.15e+14      0.000     184.256     184.256
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Seleção de Produtos;Avaliações;Reputação da Marca;Desconto/Promoções;Conveniência;Other;   112.5790   6.27e-13    1.8e+14      0.000     112.579     112.579
Que fatores influenciam a sua decisão de fazer compras online? (Selecione todas as opções aplicáveis: Conveniência, Preço, Seleção de Produtos, Avaliações, Reputação da Marca, Descontos/Promoções,..._Preço;Seleção de Produtos;Reputação da Marca;                                                     20.2902   1.15e-12   1.77e+13      0.000      20.290      20.290

In [112]:
for i in range(0, X.shape[0]):
    model.predict([1] + X.iloc[i].tolist())

    print(f'Observação: {i + 1}')
    print(f'Previsão: {model.predict([1] + X.iloc[i].tolist())[0]:.2f}')
    print(f'Valor real: {y.iloc[i]:.2f}')
    print('=' * 18)

Observação: 1
Previsão: 300.00
Valor real: 300.00
==================
Observação: 2
Previsão: 100.00
Valor real: 100.00
==================
Observação: 3
Previsão: 200.00
Valor real: 200.00
==================
Observação: 4
Previsão: 200.00
Valor real: 200.00
==================
Observação: 5
Previsão: 200.00
Valor real: 200.00
==================
Observação: 6
Previsão: 200.00
Valor real: 200.00
==================
Observação: 7
Previsão: 300.00
Valor real: 300.00
==================
Observação: 8
Previsão: 500.00
Valor real: 500.00
==================
Observação: 9
Previsão: 400.00
Valor real: 400.00
==================
Observação: 10
Previsão: 200.00
Valor real: 200.00
==================
Observação: 11
Previsão: 200.00
Valor real: 200.00
==================
Observação: 12
Previsão: 200.00
Valor real: 200.00
==================
Observação: 13
Previsão: 100.00
Valor real: 100.00
==================
Observação: 14
Previsão: 500.00
Valor real: 500.00
==================
Observação: 15
Previsão: 150.00
Valor real: 150.00
==================
Observação: 16
Previsão: 200.00
Valor real: 200.00
==================
Observação: 17
Previsão: 240.00
Valor real: 240.00
==================
Observação: 18
Previsão: 50.00
Valor real: 50.00
==================
Observação: 19
Previsão: 199.00
Valor real: 199.00
==================
Observação: 20
Previsão: 250.00
Valor real: 250.00
==================
Observação: 21
Previsão: 200.00
Valor real: 200.00
==================
Observação: 22
Previsão: 69.00
Valor real: 69.00
==================
Observação: 23
Previsão: 500.00
Valor real: 500.00
==================
Observação: 24
Previsão: 110.00
Valor real: 110.00
==================
Observação: 25
Previsão: 500.00
Valor real: 500.00
==================
Observação: 26
Previsão: 350.00
Valor real: 350.00
==================
Observação: 27
Previsão: 350.00
Valor real: 350.00
==================
Observação: 28
Previsão: 350.00
Valor real: 350.00
==================
Observação: 29
Previsão: 350.00
Valor real: 350.00
==================
Observação: 30
Previsão: 400.00
Valor real: 400.00
==================
Observação: 31
Previsão: 199.00
Valor real: 199.00
==================
Observação: 32
Previsão: 600.00
Valor real: 600.00
==================
Observação: 33
Previsão: 400.00
Valor real: 400.00
==================
Observação: 34
Previsão: 500.00
Valor real: 500.00
==================
Observação: 35
Previsão: 300.00
Valor real: 300.00
==================
Observação: 36
Previsão: 250.00
Valor real: 250.00
==================
Observação: 37
Previsão: 600.00
Valor real: 600.00
==================
Observação: 38
Previsão: 150.00
Valor real: 150.00
==================
Observação: 39
Previsão: 400.00
Valor real: 400.00
==================
Observação: 40
Previsão: 350.00
Valor real: 350.00
==================

# Respostas:
1) O modelo é significativo?
    - Sim, o modelo é significativo, pois o p-value é menor que 0.05 indicando que a hipótese nula de que os parâmetros são iguais a zero é rejeitada.
2) Os parametros são significativos? O que isso significa?
    - Sim, os parâmetros são significativos. Isso significa que as variáveis independentes são capazes de explicar a variabilidade da variável dependente.
3) Qual o valor do coeficiente de determinação? O que isso significa?
    - O valor do coeficiente de determinação é 1.0. Isso significa que o modelo é capaz de explicar 100% da variabilidade da variável dependente.
4) Caso exista parametros não significativos, o que vocês fariam para melhorar o modelo?
    - Caso existisse parâmetros não significativos, seria necessário realizar uma análise mais aprofundada dos dados, talvez utilizando outras variáveis ou até mesmo outras técnicas de regressão. Porém, como o modelo é significativo e os parâmetros também, não é necessário realizar nenhuma melhoria.
5) Conclusões finais
    - O modelo é significativo e os parâmetros são significativos, o que significa que o modelo é capaz de explicar 100% da variabilidade da variável dependente. Portanto, o modelo é adequado para prever a o valor médio que o cliente gasta quando faz uma compra online com base nas variáveis independentes.

In [113]:
# Provando que houve overfitting no modelo

# ===================================================================================================
# Dividindo o dataset em treino e teste                                                               |
# ===================================================================================================
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = sm.OLS(y_train, sm.add_constant(X_train)).fit()

y_pred = model.predict(sm.add_constant(X_test))

print('Dividindo o dataset em treino e teste')
print(f'R2: {model.rsquared:.2f}')
print(f'MSE: {mean_squared_error(y_test, y_pred):.2f}')
print(f'RMSE: {mean_squared_error(y_test, y_pred, squared=False):.2f}', end='\n\n')

# ===================================================================================================
# Usando cross-validation                                                                           |
# ===================================================================================================
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

model = sm.OLS(y, sm.add_constant(X)).fit()

lr_estimator = LinearRegression()

scores = cross_val_score(lr_estimator, X, y, cv=5, scoring='neg_mean_squared_error')

print('Usando cross-validation')
print(f'R2: {scores.mean():.2f}')
print(f'MSE: {scores.mean():.2f}')
print(f'RMSE: {abs(scores.mean()) ** 0.5:.2f}', end='\n\n')

# ===================================================================================================
# Usando Ridge Regression                                                                           |
# ===================================================================================================
from sklearn.linear_model import Ridge

model = Ridge(alpha=1.0)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print('Usando Ridge Regression')
print(f'R2: {model.score(X_test, y_test):.2f}')
print(f'MSE: {mean_squared_error(y_test, y_pred):.2f}')
print(f'RMSE: {mean_squared_error(y_test, y_pred, squared=False):.2f}', end='\n\n')

Dividindo o dataset em treino e teste
R2: 1.00
MSE: 40161.88
RMSE: 200.40

Usando cross-validation
R2: -104260.53
MSE: -104260.53
RMSE: 322.89

Usando Ridge Regression
R2: -1.36
MSE: 16018.01
RMSE: 126.56

/home/pedro/Codes/data-science-techniques/.venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
/home/pedro/Codes/data-science-techniques/.venv/lib/python3.12/site-packages/sklearn/metrics/_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

# Caso de overfitting no modelo:
- Foi notado que o modelo apresenta overfitting, pois o valor do coeficiente de determinação é 1.0, o que significa que o modelo é capaz de explicar 100% da variabilidade da variável dependente. Isso indica que o modelo está se ajustando muito bem aos dados de treinamento, mas não é capaz de generalizar para novos dados. Para evitar o overfitting, seria necessário utilizar técnicas de regularização, como Lasso ou Ridge, ou até mesmo reduzir o número de variáveis independentes.

Posteriormente, utilizamos 3 técnicas para validar que o problema em questão estava com overfitting:
1. Dividimos o dataset em treino e teste. Obtivemos um MSE de 40k e um RMSE de 200, indicando que o modelo está com overfitting.
2. Utilizamos a técnica de validação cruzada com 5 folds. Obtivemos um R2 de -104k, indicando que o modelo está com overfitting.
3. Utilizamos Ridge Regression. Obtivemos um R2 de -1.36, indicando que o modelo está com overfitting.

## Conclusão:
- O overfitting ocorre quando um modelo de aprendizado de máquina se ajusta excessivamente aos dados de treinamento, capturando ruídos e padrões aleatórios que não são representativos da verdadeira relação entre as variáveis. Isso leva a um desempenho deficiente quando o modelo é aplicado a novos dados, pois ele não generaliza bem. É prejudicial porque compromete a capacidade do modelo de fazer previsões precisas e úteis em situações do mundo real.
- Posteriormente na etapa 5, veremos que a premissa do desempenho deficiente para novos dados irá se confirmar.